### ISSUE TITLE
cannot replicate the results

### ISSUE THREAD

**Issue by zydonghku** [GabrieleRovigatti/prodest#12] opened 2019-10-10 05:46 UTC
Hi Gabriele,

Thank you for this powerful package!

My problem is, I ran the code twice and got different results. The problem is still here even I use your example code in the help files.  Is there anything wrong so that I cannot replicate the results? BTW, I also find that estimated coefficients will also be changed if I use different reps(#). Based on my knowledge, it will only change the s.e. instead of the coeff. Please tell me if I am wrong.

Best regards,
Zhanyu

**Comment by GabrieleRovigatti** [comment] 2019-10-10 08:49
Dear Zhanyu,

thanks for the message. 

Could you please provide some additional details (like, a MWE to make the issue reproducible on my system, possibly any detail on the system you are running on - R version, Rstudio version if any, windows/Linux/Mac etc.) in order for me to try to tackle the issue?

Thanks,

Gabriele

**Comment by zydonghku** [comment] 2019-10-10 12:05
Dear Gabriele,

Thank you for your reply.

I run the package (the latest version) on Stata 14.0 on the Windows system. For example, I just run the following example code provided in your help files:

`insheet using "https://raw.githubusercontent.com/GabrieleRovigatti/prodest/master/stata/data/prodest.csv", names clear`

`prodest log_y, free(log_lab1 log_lab2) state(log_k) proxy(log_investment) va met(op) acf opt(nm) reps(50) id(id) t(year)  /* run twince */ `

`prodest log_y, free(log_lab1 log_lab2) state(log_k) proxy(log_investment) va met(op) acf opt(nm) reps(30) id(id) t(year)  `

then you will see different results. 

Thanks,
Zhanyu

**Comment by GabrieleRovigatti** [comment] 2019-10-10 12:18
Dear Zhanyu,

thanks for the message and the clarifications. 

The issue you outlined with the acf models' estimation is pretty well-known (you might find a section in my paper regarding it and a relatively new paper dealing with the topic on the Journal of Applied Econometrics). It has to do with the optimization of the second stage - which is a non-linear GMM problem - and the starting points of the optimizer. It is true that - in general - such an issue would primarily affect the estimation of the standard errors during the bootstrap repetitions, but in particular cases the starting points might affect local maxima in different points of the parameter space, and give different optimization results.

A possible solution would be to set the seed **before** running the estimation.

I hope to have clarified,

**Comment by zydonghku** [comment] 2019-10-10 12:45
Dear Gabriele,

Thank you for your reply.

Firstly, I tried to use your seed() option, but it reported the error "option seed() not allowed".  I opened your ado file but found that you did not set the seed option in -prodest-, then I manually set the seed (-set the seed #- before running the estimation ) but still got the different results.
Secondly, my understanding is that at the first stage, you obtain starting points from a simple OLS at the first stage. If there is no any other randomness, we will have the same/consistent starting points through the OLS estimation, and thus, the estimated coefficients will not be changed no matter what optimization method we use. But I can still see the different estimated coefficients. Please inform me if I am wrong. Thanks.

Best regards,
Zhanyu

**Comment by GabrieleRovigatti** [comment] 2019-10-10 13:19
Dear Zhanyu,

I have discontinued the option seed() in prodest. What I was suggesting was to add "set seed <whatever number>" before running **every** estimation, in a way that every run of prodest runs on the same seed number. 

Let me clarify on the first-stage / second-stage question: you rightfully outline that the first stage is a simple OLS estimation, but as you might know the ACF correction consists exactly in **overcoming** the first-stage results, and only rely on the second-stage results, also for the free variable parameter. In a nutshell, then, without acf correction you could run into the same issue, but for the state and proxy variables only. 

To a more "official" side, I will close the issue because - on my system, at least - the following works and gives the same results every time 

```
insheet using "https://raw.githubusercontent.com/GabrieleRovigatti/prodest/master/stata/data/prodest.csv", names clear
set seed 101
prodest log_y, free(log_lab1 log_lab2) state(log_k) proxy(log_investment) va met(op) acf opt(nm) reps(50) id(id) t(year) 
set seed 101
prodest log_y, free(log_lab1 log_lab2) state(log_k) proxy(log_investment) va met(op) acf opt(nm) reps(50) id(id) t(year) 
```

whereas, for different results in different rounds of estimation in the acf framework, please refer to my paper [here](https://journals.sagepub.com/doi/pdf/10.1177/1536867X1801800307). 

Best,

Gabriele

**Closed as completed by GabrieleRovigatti** 2019-10-10 13:19 UTC

**Comment by zydonghku** [comment] 2019-10-10 13:31
Ok, thank you again for your reply. Hope to see your name on the AER in the near future :)

Best regards,
Zhanyu
